[settings]
experimental = true

[env]
MISE_EXPERIMENTAL = 1
MISE_YES = 1
MISE_TRUST = 1

[tools]
bun = "latest"
node = "24"
shfmt = "latest"
shellcheck = "latest"
yq = "latest"
"npm:sort-package-json" = "latest"
uv = "latest"

[prepare]
[prepare.bun]
auto = true
