import {
  ARTIFACT_FORMAT_VERSION,
  PREPARED_CALL_VERSION,
  RUNTIME_CONTRACT_VERSION,
} from "../src/runtime/index.ts";

void [ARTIFACT_FORMAT_VERSION, PREPARED_CALL_VERSION, RUNTIME_CONTRACT_VERSION];
